"""Lower an optimized IR graph to a CUDA module.

This is the orchestration layer between the graph and the kernels: it walks the
(fused) IR, picks a schedule per GEMM, emits the distinct kernel sources, and
builds an ordered launch plan with concrete grid/block dims (shapes are static
after shape inference) and buffer bindings.

Two consumers use the result:
  * ``mdlc.codegen.cuda.nvrtc_runtime`` — JIT-compiles and launches on a GPU.
  * ``simulate_module`` here — executes the same plan on CPU via the kernel
    simulator (with host fallbacks for ops we don't yet codegen), proving the
    generated kernels compose correctly end-to-end without a device.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Optional

import numpy as np

from mdlc.codegen.schedule import (
    DEFAULT_DEPTHWISE,
    DEFAULT_GEMM,
    DepthwiseSchedule,
    GemmSchedule,
)
from mdlc.codegen.cuda import templates as T
from mdlc.ir import VIEW_OPS, Graph, Node
from mdlc.runtime import ops

ScheduleFn = Callable[[Node, tuple], GemmSchedule]

# Ops we currently execute on the host (reference NumPy) rather than via a
# generated kernel. They're cheap, shape-shuffling, or reductions whose CUDA
# templates aren't the focus; a production compiler would lower these too.
HOST_FALLBACK = {
    "MaxPool", "AveragePool", "GlobalAveragePool", "Flatten", "Reshape",
    "Transpose", "Concat", "Squeeze", "Unsqueeze", "Pad", "Softmax", "Identity",
}

# Pointwise ops the elementwise emitter can lower, fused or standalone.
ELEMENTWISE_OPS = {
    "Relu", "Sigmoid", "Tanh", "HardSwish", "Clip", "Add", "Mul", "Sub", "Div",
    "LeakyRelu", "HardSigmoid", "Erf",
}

# Metadata-only reshapes (canonical set lives in mdlc.ir — the memory
# planner's alias-aware liveness must agree with codegen's zero-launch views).


@dataclass
class Launch:
    """One kernel invocation in the execution plan."""
    kind: str                       # "gemm" | "im2col" | "elementwise" | "host"
    kernel_name: str
    inputs: list[str]               # tensor edge names, in kernel arg order
    outputs: list[str]
    grid: tuple
    block: tuple
    meta: dict = field(default_factory=dict)


@dataclass
class CudaModule:
    graph: Graph
    kernels: dict[str, str]         # kernel name -> CUDA source (deduplicated)
    plan: list[Launch]
    scratch_shapes: dict[str, tuple]

    def sources(self) -> str:
        """Concatenate all distinct kernels into one .cu translation unit."""
        header = "// Auto-generated by mdlc. Distinct fused kernels below.\n"
        return header + "\n\n".join(self.kernels[k] for k in sorted(self.kernels))

    def fallbacks(self) -> list[str]:
        """One label per host-executed launch, e.g. ``Conv(group=32)``.

        A compiler that quietly runs ops on the CPU is a demo, so every host
        fallback is named in the compile report until it is burned down.
        """
        labels = []
        for l in self.plan:
            if l.kind != "host":
                continue
            node = l.meta.get("node")
            label = node.op_type if node is not None else l.kernel_name
            if node is not None and node.attrs.get("group", 1) != 1:
                label += f"(group={node.attrs['group']})"
            labels.append(label)
        return labels

    def report(self) -> str:
        kinds: dict[str, int] = {}
        for l in self.plan:
            kinds[l.kind] = kinds.get(l.kind, 0) + 1
        lines = [f"CUDA module: {len(self.kernels)} distinct kernels, "
                 f"{len(self.plan)} launches"]
        lines.append("  launches by kind: " +
                     ", ".join(f"{k}x{v}" for k, v in sorted(kinds.items())))
        fb: dict[str, int] = {}
        for label in self.fallbacks():
            fb[label] = fb.get(label, 0) + 1
        if fb:
            lines.append("  host fallbacks: " +
                         ", ".join(f"{k}x{v}" for k, v in sorted(fb.items())))
        else:
            lines.append("  host fallbacks: none")
        return "\n".join(lines)


class CudaCodegen:
    def __init__(self, schedule_fn: Optional[ScheduleFn] = None,
                 dw_schedule_fn=None) -> None:
        self.schedule_fn = schedule_fn or (lambda node, mnk: DEFAULT_GEMM)
        self.dw_schedule_fn = dw_schedule_fn or (lambda node, sig: DEFAULT_DEPTHWISE)
        self.kernels: dict[str, str] = {}
        self.plan: list[Launch] = []
        self.scratch: dict[str, tuple] = {}
        self._gemm_cache: dict[tuple, str] = {}
        self._dw_cache: dict[tuple, str] = {}
        self._reduce_cache: dict[tuple, str] = {}
        self._ew_count = 0
        self._has_im2col = False

    # -- helpers --------------------------------------------------------

    def _shape(self, g: Graph, name: str) -> tuple:
        info = g.info(name)
        if info is None or not info.is_static:
            raise ValueError(f"{name!r} lacks a static shape; run shape inference")
        return tuple(int(d) for d in info.shape)

    def _emit_gemm(self, M, N, K, *, with_bias, bias_mode, activation, attrs,
                   trans_a: bool = False, trans_b: bool = False) -> str:
        sched = self.schedule_fn(None, (M, N, K))
        # trans_a/trans_b are part of the identity: they change the emitted
        # load indices, so a transposed Gemm must not reuse a plain one's kernel.
        sig = (sched.key(), with_bias, bias_mode, activation,
               attrs.get("clip_min"), attrs.get("clip_max"), attrs.get("alpha"),
               attrs.get("beta"), trans_a, trans_b)
        if sig in self._gemm_cache:
            return self._gemm_cache[sig]
        tag = f"{'ta' if trans_a else ''}{'tb' if trans_b else ''}" or "nt"
        name = (f"gemm_{sched.key()}_{activation or 'none'}_{bias_mode}_{tag}"
                f"_{len(self._gemm_cache)}")
        _, src = T.gemm_kernel(name, sched, with_bias=with_bias,
                               bias_mode=bias_mode, activation=activation,
                               attrs=attrs, trans_a=trans_a, trans_b=trans_b)
        self.kernels[name] = src
        self._gemm_cache[sig] = name
        return name

    def _grid_block_gemm(self, M, N, sched: GemmSchedule):
        gx = (N + sched.BN - 1) // sched.BN
        gy = (M + sched.BM - 1) // sched.BM
        return (gx, gy, 1), (sched.threads_per_block(), 1, 1)

    # -- per-op lowering ------------------------------------------------

    def lower(self, g: Graph) -> CudaModule:
        for node in g.topo_sort():
            op = node.op_type
            if op in ("Conv", "FusedConvAct", "FusedConvBNAct"):
                self._lower_conv(g, node)
            elif op in ("Gemm", "FusedGemmAct"):
                self._lower_gemm(g, node)
            elif op == "MatMul":
                self._lower_matmul(g, node)
            elif op == "FusedElementwise":
                self._lower_elementwise(g, node)
            elif op == "GlobalAveragePool":
                self._lower_reduce_hw(g, node)
            elif op == "ReduceMean" and self._is_hw_mean(g, node):
                self._lower_reduce_hw(g, node)
            elif op == "MaxPool" and node.attrs.get("ceil_mode", 0) == 0:
                self._lower_maxpool(g, node)
            elif op in VIEW_OPS:
                # Pure metadata: same bytes, new shape. Never a kernel, never
                # a host fallback — the runtime aliases the buffer.
                self.plan.append(Launch(
                    "view", op, [node.inputs[0]], [node.outputs[0]], (), (),
                    meta={"out_shape": self._shape(g, node.outputs[0]),
                          "node": node}))
            elif op in ELEMENTWISE_OPS:
                # A lone elementwise op (e.g. MobileNetV2's bare residual Add:
                # linear bottlenecks leave no activation to chain) lowers
                # through the same fused-elementwise emitter as a
                # one-node subgraph — never to host.
                single = Node("FusedElementwise", list(node.inputs),
                              [o for o in node.outputs if o],
                              attrs={"subgraph": [node]},
                              name=(node.name or op) + "_single")
                self._lower_elementwise(g, single)
            elif op in HOST_FALLBACK:
                self.plan.append(Launch("host", op, node.real_inputs(),
                                        [o for o in node.outputs if o],
                                        (), (), meta={"node": node}))
            else:
                raise NotImplementedError(f"codegen: no lowering for {op!r}")
        return CudaModule(g, self.kernels, self.plan, self.scratch)

    def _lower_conv(self, g: Graph, node: Node) -> None:
        x, w = node.inputs[0], node.inputs[1]
        has_bias = len(node.inputs) > 2 and node.inputs[2]
        xs = self._shape(g, x)            # (N, C, H, W)
        ws = self._shape(g, w)            # (OC, C, KH, KW)
        ys = self._shape(g, node.outputs[0])  # (N, OC, OH, OW)
        n, C, H, W = xs
        OC, _, KH, KW = ws
        _, _, OH, OW = ys
        a = node.attrs
        SH, SW = a.get("strides", [1, 1])
        DH, DW = a.get("dilations", [1, 1])
        pads = a.get("pads") or [0, 0, 0, 0]
        PH, PW = pads[0], pads[1]
        group = a.get("group", 1)

        # Depthwise (group == C_in, one input channel per output channel):
        # direct kernel — im2col would multiply memory traffic by KH*KW for
        # zero GEMM benefit. Covers channel multiplier m >= 1.
        if group == C and ws[1] == 1:
            self._lower_depthwise(g, node, xs=xs, ws=ws, ys=ys,
                                  SH=SH, SW=SW, PH=PH, PW=PW, DH=DH, DW=DW)
            return

        # General grouped conv (1 < group < C_in): rare in the target models,
        # correctness-first — per-group slices through the im2col+GEMM path,
        # still on device (no host fallback).
        if group != 1:
            self._lower_grouped(g, node, xs=xs, ws=ws, ys=ys, group=group,
                                SH=SH, SW=SW, PH=PH, PW=PW, DH=DH, DW=DW)
            return

        if not self._has_im2col:
            nm, src = T.im2col_kernel("im2col")
            self.kernels[nm] = src
            self._has_im2col = True

        K = C * KH * KW
        P = OH * OW
        cols = node.outputs[0] + "__cols"
        self.scratch[cols] = (K, P)
        bx, byd = 16, 16

        activation = node.attrs.get("activation")
        kname = self._emit_gemm(OC, P, K, with_bias=bool(has_bias),
                                bias_mode="row", activation=activation, attrs=node.attrs)
        sched = self.schedule_fn(None, (OC, P, K))
        grid, block = self._grid_block_gemm(OC, P, sched)
        inputs = [w, cols] + ([node.inputs[2]] if has_bias else [])

        # One im2col+GEMM pair per image: the column matrix holds a single
        # CHW image, so batching is an outer loop with explicit element
        # offsets into x and y (the cols scratch is reused serially). Keeps
        # the tuned GEMM shape independent of N.
        for bi in range(n):
            self.plan.append(Launch(
                "im2col", "im2col", [x], [cols],
                ((P + bx - 1) // bx, (K + byd - 1) // byd, 1), (bx, byd, 1),
                meta={"C": C, "H": H, "W": W, "KH": KH, "KW": KW, "OH": OH, "OW": OW,
                      "SH": SH, "SW": SW, "PH": PH, "PW": PW, "DH": DH, "DW": DW,
                      "batch_index": bi, "in_offset": bi * C * H * W}))
            self.plan.append(Launch(
                "gemm", kname, inputs, [node.outputs[0]], grid, block,
                meta={"M": OC, "N": P, "K": K, "with_bias": bool(has_bias),
                      "weight_2d": (OC, K), "out_4d": ys, "sched": sched,
                      "batch_index": bi, "out_offset": bi * OC * OH * OW,
                      "node": node}))

    def _lower_depthwise(self, g: Graph, node: Node, *, xs, ws, ys,
                         SH, SW, PH, PW, DH, DW) -> None:
        n, C, H, W = xs
        OC, _, KH, KW = ws
        _, _, OH, OW = ys
        mult = OC // C
        has_bias = len(node.inputs) > 2 and node.inputs[2]
        activation = node.attrs.get("activation")
        dw_sig = {"C": C, "mult": mult, "H": H, "W": W, "OH": OH, "OW": OW,
                  "KH": KH, "KW": KW, "SH": SH, "SW": SW, "PH": PH, "PW": PW,
                  "DH": DH, "DW": DW}
        sched = self.dw_schedule_fn(node, dw_sig)

        sig = ("dw", C, mult, H, W, OH, OW, KH, KW, SH, SW, PH, PW, DH, DW,
               sched.key(), bool(has_bias), activation,
               node.attrs.get("clip_min"), node.attrs.get("clip_max"),
               node.attrs.get("alpha"), node.attrs.get("beta"))
        if sig in self._dw_cache:
            kname = self._dw_cache[sig]
        else:
            kname = f"dw_{sched.key()}_{activation or 'none'}_{len(self._dw_cache)}"
            _, src = T.depthwise_conv_kernel(
                kname, C=C, mult=mult, H=H, W=W, OH=OH, OW=OW,
                KH=KH, KW=KW, SH=SH, SW=SW, PH=PH, PW=PW, DH=DH, DW=DW,
                tile_h=sched.tile_h, tile_w=sched.tile_w,
                with_bias=bool(has_bias), activation=activation,
                attrs=node.attrs, direct_load=sched.direct_load)
            self.kernels[kname] = src
            self._dw_cache[sig] = kname

        grid = ((OW + sched.tile_w - 1) // sched.tile_w,
                (OH + sched.tile_h - 1) // sched.tile_h,
                n * OC)
        inputs = [node.inputs[0], node.inputs[1]] + \
                 ([node.inputs[2]] if has_bias else [])
        self.plan.append(Launch(
            "depthwise", kname, inputs, [node.outputs[0]],
            grid, (sched.threads_per_block(), 1, 1),
            meta={"out_4d": ys, "node": node, "dw_sig": dw_sig,
                  "sched": sched}))

    def _lower_grouped(self, g: Graph, node: Node, *, xs, ws, ys, group,
                       SH, SW, PH, PW, DH, DW) -> None:
        n, C, H, W = xs
        OC, Cg, KH, KW = ws            # Cg == C // group
        _, _, OH, OW = ys
        OCg = OC // group
        has_bias = len(node.inputs) > 2 and node.inputs[2]
        activation = node.attrs.get("activation")

        if not self._has_im2col:
            nm, src = T.im2col_kernel("im2col")
            self.kernels[nm] = src
            self._has_im2col = True

        Kg = Cg * KH * KW
        P = OH * OW
        cols = node.outputs[0] + "__cols"
        self.scratch[cols] = (Kg, P)
        bx, byd = 16, 16
        kname = self._emit_gemm(OCg, P, Kg, with_bias=bool(has_bias),
                                bias_mode="row", activation=activation,
                                attrs=node.attrs)
        sched = self.schedule_fn(None, (OCg, P, Kg))
        grid, block = self._grid_block_gemm(OCg, P, sched)
        inputs = [node.inputs[1], cols] + ([node.inputs[2]] if has_bias else [])

        for bi in range(n):
            for gi in range(group):
                self.plan.append(Launch(
                    "im2col", "im2col", [node.inputs[0]], [cols],
                    ((P + bx - 1) // bx, (Kg + byd - 1) // byd, 1), (bx, byd, 1),
                    meta={"C": Cg, "H": H, "W": W, "KH": KH, "KW": KW,
                          "OH": OH, "OW": OW, "SH": SH, "SW": SW,
                          "PH": PH, "PW": PW, "DH": DH, "DW": DW,
                          "batch_index": bi, "c_range": (gi * Cg, (gi + 1) * Cg),
                          "in_offset": (bi * C + gi * Cg) * H * W}))
                self.plan.append(Launch(
                    "gemm", kname, inputs, [node.outputs[0]], grid, block,
                    meta={"M": OCg, "N": P, "K": Kg, "with_bias": bool(has_bias),
                          "weight_2d": (OC, Kg), "w_rows": (gi * OCg, (gi + 1) * OCg),
                          "out_4d": ys, "batch_index": bi, "sched": sched,
                          "oc_range": (gi * OCg, (gi + 1) * OCg),
                          "out_offset": (bi * OC + gi * OCg) * OH * OW,
                          "node": node}))

    def _is_hw_mean(self, g: Graph, node: Node) -> bool:
        """True when this ReduceMean is a spatial mean over H,W of an NCHW
        tensor (both SE squeezes and classifier-head pooling)."""
        try:
            xs = self._shape(g, node.inputs[0])
        except ValueError:
            return False
        if len(xs) != 4:
            return False
        axes = node.attrs.get("axes")
        if axes is None and len(node.inputs) > 1 and node.inputs[1]:
            if not g.is_constant(node.inputs[1]):
                return False
            axes = g.initializers[node.inputs[1]].tolist()
        if axes is None:
            return False
        return sorted(int(a) % 4 for a in np.atleast_1d(axes)) == [2, 3]

    def _lower_reduce_hw(self, g: Graph, node: Node) -> None:
        xs = self._shape(g, node.inputs[0])       # (N, C, H, W)
        n, C, H, W = xs
        block = 128
        sig = ("reduce_hw", H * W, block)
        if sig in self._reduce_cache:
            kname = self._reduce_cache[sig]
        else:
            kname = f"reduce_mean_hw_{len(self._reduce_cache)}"
            _, src = T.reduce_mean_hw_kernel(kname, HW=H * W, block=block)
            self.kernels[kname] = src
            self._reduce_cache[sig] = kname
        self.plan.append(Launch(
            "reduce", kname, [node.inputs[0]], [node.outputs[0]],
            (n * C, 1, 1), (block, 1, 1),
            meta={"out_shape": self._shape(g, node.outputs[0]),
                  "out_n": n * C, "node": node}))

    def _lower_maxpool(self, g: Graph, node: Node) -> None:
        xs = self._shape(g, node.inputs[0])
        ys = self._shape(g, node.outputs[0])
        n, C, H, W = xs
        _, _, OH, OW = ys
        a = node.attrs
        KH, KW = a["kernel_shape"]
        SH, SW = a.get("strides", [1, 1])
        pads = a.get("pads") or [0, 0, 0, 0]
        DH, DW = a.get("dilations", [1, 1])
        total = n * C * OH * OW
        block = 128
        kname = f"maxpool_{len([k for k in self.kernels if k.startswith('maxpool')])}"
        _, src = T.maxpool_kernel(kname, H=H, W=W, OH=OH, OW=OW, KH=KH, KW=KW,
                                  SH=SH, SW=SW, PH=pads[0], PW=pads[1],
                                  DH=DH, DW=DW, total=total, block=block)
        self.kernels[kname] = src
        self.plan.append(Launch(
            "pool", kname, [node.inputs[0]], [node.outputs[0]],
            ((total + block - 1) // block, 1, 1), (block, 1, 1),
            meta={"out_shape": ys, "out_n": total, "node": node}))

    def _lower_gemm(self, g: Graph, node: Node) -> None:
        a = node.attrs
        transA = a.get("transA", 0)
        transB = a.get("transB", 0)
        A, B = node.inputs[0], node.inputs[1]
        has_bias = len(node.inputs) > 2 and node.inputs[2]
        ashape = self._shape(g, A)
        bshape = self._shape(g, B)
        M = ashape[1] if transA else ashape[0]
        K = ashape[0] if transA else ashape[1]
        N = bshape[0] if transB else bshape[1]
        # ONNX Gemm is Y = alpha*A'*B' + beta*C, but the emitted epilogue only
        # computes A'*B' + bias. Inference exports emit alpha=beta=1.0; any
        # other value would be applied by neither executor, so fail loudly at
        # lowering time rather than return a quietly wrong tensor (GAPS §9.1).
        alpha = float(a.get("alpha", 1.0))
        beta = float(a.get("beta", 1.0))
        if alpha != 1.0 or (has_bias and beta != 1.0):
            raise NotImplementedError(
                f"Gemm {node.name or node.outputs[0]!r}: alpha={alpha} beta={beta}; "
                "the GEMM epilogue applies neither (only A*B + bias). Fold them "
                "into the weights/bias before lowering.")
        activation = a.get("activation")
        kname = self._emit_gemm(M, N, K, with_bias=bool(has_bias),
                                bias_mode="col", activation=activation,
                                attrs=node.attrs,
                                trans_a=bool(transA), trans_b=bool(transB))
        sched = self.schedule_fn(None, (M, N, K))
        grid, block = self._grid_block_gemm(M, N, sched)
        inputs = [A, B] + ([node.inputs[2]] if has_bias else [])
        self.plan.append(Launch("gemm", kname, inputs, [node.outputs[0]], grid, block,
                                meta={"M": M, "N": N, "K": K, "transA": transA,
                                      "transB": transB, "alpha": alpha,
                                      "beta": beta, "sched": sched,
                                      "with_bias": bool(has_bias), "node": node}))

    def _lower_matmul(self, g: Graph, node: Node) -> None:
        A, B = node.inputs[0], node.inputs[1]
        M, K = self._shape(g, A)[-2:]
        N = self._shape(g, B)[-1]
        kname = self._emit_gemm(M, N, K, with_bias=False, bias_mode="col",
                                activation=None, attrs={})
        sched = self.schedule_fn(None, (M, N, K))
        grid, block = self._grid_block_gemm(M, N, sched)
        self.plan.append(Launch("gemm", kname, [A, B], [node.outputs[0]], grid, block,
                                meta={"M": M, "N": N, "K": K, "with_bias": False,
                                      "sched": sched, "node": node}))

    def _lower_elementwise(self, g: Graph, node: Node) -> None:
        # Every external input must be a compile-time scalar or a static shape
        # broadcastable to the output (stride-0 indexing on broadcast dims);
        # every group output must be output-shaped. Anything else -> host.
        out_shape = self._shape(g, node.outputs[0])
        out_n = int(np.prod(out_shape))
        scalar_consts: dict[str, float] = {}
        input_shapes: dict[str, tuple] = {}
        ok = True
        for e in self._ext_inputs(node):
            shape = (tuple(g.initializers[e].shape) if g.is_constant(e)
                     else self._shape(g, e))
            if g.is_constant(e) and g.initializers[e].size == 1:
                scalar_consts[e] = float(g.initializers[e].reshape(()))
                continue
            try:
                T.broadcast_index_expr(shape, out_shape)
            except ValueError:
                ok = False
                break
            input_shapes[e] = shape
        if ok:
            for o in node.outputs:
                if int(np.prod(self._shape(g, o))) != out_n:
                    ok = False
                    break
        if not ok:
            self.plan.append(Launch("host", "FusedElementwise", node.real_inputs(),
                                    list(node.outputs), (), (), meta={"node": node}))
            return

        name = f"fused_ew_{self._ew_count}"
        self._ew_count += 1
        kname, src, ext = T.elementwise_kernel(
            name, node, scalar_consts=scalar_consts,
            input_shapes=input_shapes, out_shape=out_shape)
        self.kernels[kname] = src
        block = 128
        grid = ((out_n + block - 1) // block, 1, 1)
        self.plan.append(Launch("elementwise", kname, ext, list(node.outputs),
                                grid, (block, 1, 1),
                                meta={"N": out_n, "out_shape": out_shape, "node": node,
                                      "scalar_consts": scalar_consts}))

    def _ext_inputs(self, node: Node) -> list[str]:
        sub = node.attrs["subgraph"]
        internal = {o for n in sub for o in n.outputs if o}
        ext, seen = [], set()
        for n in sub:
            for e in n.real_inputs():
                if e not in internal and e not in seen:
                    seen.add(e)
                    ext.append(e)
        return ext


def emit_cuda_module(graph: Graph, schedule_fn: Optional[ScheduleFn] = None,
                     dw_schedule_fn=None) -> CudaModule:
    return CudaCodegen(schedule_fn, dw_schedule_fn).lower(graph)
