"""Lower an optimized IR graph to a CUDA module.

This is the orchestration layer between the graph and the kernels: it walks the
(fused) IR, picks a schedule per GEMM, emits the distinct kernel sources, and
builds an ordered launch plan with concrete grid/block dims (shapes are static
after shape inference) and buffer bindings.

Two consumers use the result:
  * ``mdlc.codegen.cuda.nvrtc_runtime`` — JIT-compiles and launches on a GPU.
  * ``simulate_module`` here — executes the same plan on CPU via the kernel
    simulator (with host fallbacks for ops we don't yet codegen), proving the
    generated kernels compose correctly end-to-end without a device.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Optional

import numpy as np

from mdlc.codegen.schedule import DEFAULT_GEMM, GemmSchedule
from mdlc.codegen.cuda import templates as T
from mdlc.ir import Graph, Node
from mdlc.runtime import ops

ScheduleFn = Callable[[Node, tuple], GemmSchedule]

# Ops we currently execute on the host (reference NumPy) rather than via a
# generated kernel. They're cheap, shape-shuffling, or reductions whose CUDA
# templates aren't the focus; a production compiler would lower these too.
HOST_FALLBACK = {
    "MaxPool", "AveragePool", "GlobalAveragePool", "Flatten", "Reshape",
    "Transpose", "Concat", "Squeeze", "Unsqueeze", "Pad", "Softmax", "Identity",
}


@dataclass
class Launch:
    """One kernel invocation in the execution plan."""
    kind: str                       # "gemm" | "im2col" | "elementwise" | "host"
    kernel_name: str
    inputs: list[str]               # tensor edge names, in kernel arg order
    outputs: list[str]
    grid: tuple
    block: tuple
    meta: dict = field(default_factory=dict)


@dataclass
class CudaModule:
    graph: Graph
    kernels: dict[str, str]         # kernel name -> CUDA source (deduplicated)
    plan: list[Launch]
    scratch_shapes: dict[str, tuple]

    def sources(self) -> str:
        """Concatenate all distinct kernels into one .cu translation unit."""
        header = "// Auto-generated by mdlc. Distinct fused kernels below.\n"
        return header + "\n\n".join(self.kernels[k] for k in sorted(self.kernels))

    def fallbacks(self) -> list[str]:
        """One label per host-executed launch, e.g. ``Conv(group=32)``.

        A compiler that quietly runs ops on the CPU is a demo, so every host
        fallback is named in the compile report until it is burned down.
        """
        labels = []
        for l in self.plan:
            if l.kind != "host":
                continue
            node = l.meta.get("node")
            label = node.op_type if node is not None else l.kernel_name
            if node is not None and node.attrs.get("group", 1) != 1:
                label += f"(group={node.attrs['group']})"
            labels.append(label)
        return labels

    def report(self) -> str:
        kinds: dict[str, int] = {}
        for l in self.plan:
            kinds[l.kind] = kinds.get(l.kind, 0) + 1
        lines = [f"CUDA module: {len(self.kernels)} distinct kernels, "
                 f"{len(self.plan)} launches"]
        lines.append("  launches by kind: " +
                     ", ".join(f"{k}x{v}" for k, v in sorted(kinds.items())))
        fb: dict[str, int] = {}
        for label in self.fallbacks():
            fb[label] = fb.get(label, 0) + 1
        if fb:
            lines.append("  host fallbacks: " +
                         ", ".join(f"{k}x{v}" for k, v in sorted(fb.items())))
        else:
            lines.append("  host fallbacks: none")
        return "\n".join(lines)


class CudaCodegen:
    def __init__(self, schedule_fn: Optional[ScheduleFn] = None) -> None:
        self.schedule_fn = schedule_fn or (lambda node, mnk: DEFAULT_GEMM)
        self.kernels: dict[str, str] = {}
        self.plan: list[Launch] = []
        self.scratch: dict[str, tuple] = {}
        self._gemm_cache: dict[tuple, str] = {}
        self._ew_count = 0
        self._has_im2col = False

    # -- helpers --------------------------------------------------------

    def _shape(self, g: Graph, name: str) -> tuple:
        info = g.info(name)
        if info is None or not info.is_static:
            raise ValueError(f"{name!r} lacks a static shape; run shape inference")
        return tuple(int(d) for d in info.shape)

    def _emit_gemm(self, M, N, K, *, with_bias, bias_mode, activation, attrs) -> str:
        sched = self.schedule_fn(None, (M, N, K))
        sig = (sched.key(), with_bias, bias_mode, activation,
               attrs.get("clip_min"), attrs.get("clip_max"), attrs.get("alpha"),
               attrs.get("beta"))
        if sig in self._gemm_cache:
            return self._gemm_cache[sig]
        name = f"gemm_{sched.key()}_{activation or 'none'}_{bias_mode}_{len(self._gemm_cache)}"
        _, src = T.gemm_kernel(name, sched, with_bias=with_bias,
                               bias_mode=bias_mode, activation=activation, attrs=attrs)
        self.kernels[name] = src
        self._gemm_cache[sig] = name
        return name

    def _grid_block_gemm(self, M, N, sched: GemmSchedule):
        gx = (N + sched.BN - 1) // sched.BN
        gy = (M + sched.BM - 1) // sched.BM
        return (gx, gy, 1), (sched.threads_per_block(), 1, 1)

    # -- per-op lowering ------------------------------------------------

    def lower(self, g: Graph) -> CudaModule:
        for node in g.topo_sort():
            op = node.op_type
            if op in ("Conv", "FusedConvAct", "FusedConvBNAct"):
                self._lower_conv(g, node)
            elif op in ("Gemm", "FusedGemmAct"):
                self._lower_gemm(g, node)
            elif op == "MatMul":
                self._lower_matmul(g, node)
            elif op == "FusedElementwise":
                self._lower_elementwise(g, node)
            elif op in HOST_FALLBACK or op in ("Relu", "Sigmoid", "Tanh",
                                               "HardSwish", "Clip", "Add", "Mul",
                                               "Sub", "Div", "LeakyRelu",
                                               "HardSigmoid"):
                self.plan.append(Launch("host", op, node.real_inputs(),
                                        [o for o in node.outputs if o],
                                        (), (), meta={"node": node}))
            else:
                raise NotImplementedError(f"codegen: no lowering for {op!r}")
        return CudaModule(g, self.kernels, self.plan, self.scratch)

    def _lower_conv(self, g: Graph, node: Node) -> None:
        x, w = node.inputs[0], node.inputs[1]
        has_bias = len(node.inputs) > 2 and node.inputs[2]
        xs = self._shape(g, x)            # (N, C, H, W)
        ws = self._shape(g, w)            # (OC, C, KH, KW)
        ys = self._shape(g, node.outputs[0])  # (N, OC, OH, OW)
        n, C, H, W = xs
        OC, _, KH, KW = ws
        _, _, OH, OW = ys
        a = node.attrs
        SH, SW = a.get("strides", [1, 1])
        DH, DW = a.get("dilations", [1, 1])
        pads = a.get("pads") or [0, 0, 0, 0]
        PH, PW = pads[0], pads[1]
        group = a.get("group", 1)

        # Depthwise/grouped conv: keep on host for now (im2col-GEMM path assumes
        # group==1). Common in MobileNet/RepViT; flagged as a known gap.
        if group != 1:
            self.plan.append(Launch("host", node.op_type, node.real_inputs(),
                                    list(node.outputs), (), (), meta={"node": node}))
            return

        if not self._has_im2col:
            nm, src = T.im2col_kernel("im2col")
            self.kernels[nm] = src
            self._has_im2col = True

        K = C * KH * KW
        P = OH * OW
        cols = node.outputs[0] + "__cols"
        self.scratch[cols] = (K, P)
        bx, byd = 16, 16
        self.plan.append(Launch(
            "im2col", "im2col", [x], [cols],
            ((P + bx - 1) // bx, (K + byd - 1) // byd, 1), (bx, byd, 1),
            meta={"C": C, "H": H, "W": W, "KH": KH, "KW": KW, "OH": OH, "OW": OW,
                  "SH": SH, "SW": SW, "PH": PH, "PW": PW, "DH": DH, "DW": DW,
                  "batch": n}))

        activation = node.attrs.get("activation")
        kname = self._emit_gemm(OC, P, K, with_bias=bool(has_bias),
                                bias_mode="row", activation=activation, attrs=node.attrs)
        sched = self.schedule_fn(None, (OC, P, K))
        grid, block = self._grid_block_gemm(OC, P, sched)
        inputs = [w, cols] + ([node.inputs[2]] if has_bias else [])
        self.plan.append(Launch("gemm", kname, inputs, [node.outputs[0]],
                                grid, block,
                                meta={"M": OC, "N": P, "K": K, "with_bias": bool(has_bias),
                                      "weight_2d": (OC, K), "out_4d": ys,
                                      "node": node}))

    def _lower_gemm(self, g: Graph, node: Node) -> None:
        a = node.attrs
        transA = a.get("transA", 0)
        transB = a.get("transB", 0)
        A, B = node.inputs[0], node.inputs[1]
        has_bias = len(node.inputs) > 2 and node.inputs[2]
        ashape = self._shape(g, A)
        bshape = self._shape(g, B)
        M = ashape[1] if transA else ashape[0]
        K = ashape[0] if transA else ashape[1]
        N = bshape[0] if transB else bshape[1]
        activation = a.get("activation")
        kname = self._emit_gemm(M, N, K, with_bias=bool(has_bias),
                                bias_mode="col", activation=activation, attrs=node.attrs)
        sched = self.schedule_fn(None, (M, N, K))
        grid, block = self._grid_block_gemm(M, N, sched)
        inputs = [A, B] + ([node.inputs[2]] if has_bias else [])
        self.plan.append(Launch("gemm", kname, inputs, [node.outputs[0]], grid, block,
                                meta={"M": M, "N": N, "K": K, "transA": transA,
                                      "transB": transB, "alpha": a.get("alpha", 1.0),
                                      "beta": a.get("beta", 1.0),
                                      "with_bias": bool(has_bias), "node": node}))

    def _lower_matmul(self, g: Graph, node: Node) -> None:
        A, B = node.inputs[0], node.inputs[1]
        M, K = self._shape(g, A)[-2:]
        N = self._shape(g, B)[-1]
        kname = self._emit_gemm(M, N, K, with_bias=False, bias_mode="col",
                                activation=None, attrs={})
        sched = self.schedule_fn(None, (M, N, K))
        grid, block = self._grid_block_gemm(M, N, sched)
        self.plan.append(Launch("gemm", kname, [A, B], [node.outputs[0]], grid, block,
                                meta={"M": M, "N": N, "K": K, "with_bias": False,
                                      "node": node}))

    def _lower_elementwise(self, g: Graph, node: Node) -> None:
        # Fuse only if every external input matches the output element count and
        # any constant operands are scalar; otherwise fall back to host.
        out_shape = self._shape(g, node.outputs[0])
        out_n = int(np.prod(out_shape))
        scalar_consts: dict[str, float] = {}
        ok = True
        for e in self._ext_inputs(node):
            if g.is_constant(e):
                arr = g.initializers[e]
                if arr.size == 1:
                    scalar_consts[e] = float(arr.reshape(()))
                else:
                    ok = False
                    break
            else:
                if int(np.prod(self._shape(g, e))) != out_n:
                    ok = False
                    break
        if not ok:
            self.plan.append(Launch("host", "FusedElementwise", node.real_inputs(),
                                    list(node.outputs), (), (), meta={"node": node}))
            return

        name = f"fused_ew_{self._ew_count}"
        self._ew_count += 1
        kname, src, ext = T.elementwise_kernel(name, node, scalar_consts=scalar_consts)
        self.kernels[kname] = src
        block = 128
        grid = ((out_n + block - 1) // block, 1, 1)
        self.plan.append(Launch("elementwise", kname, ext, list(node.outputs),
                                grid, (block, 1, 1),
                                meta={"N": out_n, "node": node, "scalar_consts": scalar_consts}))

    def _ext_inputs(self, node: Node) -> list[str]:
        sub = node.attrs["subgraph"]
        internal = {o for n in sub for o in n.outputs if o}
        ext, seen = [], set()
        for n in sub:
            for e in n.real_inputs():
                if e not in internal and e not in seen:
                    seen.add(e)
                    ext.append(e)
        return ext


def emit_cuda_module(graph: Graph, schedule_fn: Optional[ScheduleFn] = None) -> CudaModule:
    return CudaCodegen(schedule_fn).lower(graph)
